### ISSUE TITLE
Diagram / Document Architecture

### ISSUE THREAD

**Issue by jhunt** [bolo/bolo-website#4]
Diagram the complete architecture of bolo, all parts, subscribers and utilities, including those we haven't built yet (like https://github.com/bolo/bolo/issues/4).  Hopefully this gives us some direction on the pieces that we still need to build, and some idea for a good, consistent naming scheme for constituent parts (dbolo, bcache, bolo2$thing, etc.)

**Comment by filefrog** [comment]
![arch overview](https://cloud.githubusercontent.com/assets/20047/10065295/946d3a9c-6251-11e5-91b3-0bcece1bdf80.png)

v0.1

**Comment by filefrog** [comment]
I'm thinking we rename dbolo `bolo-feeder`, and `bolo buffer` becomes `bolo-cacher`

**Comment by jhunt** [comment]
This is documented in the RFC now: https://github.com/bolo/rfc/blob/master/draft-hunt-tsdp-00.txt#L201-L214
